# Generated by Django 5.2.6 on 2025-09-18 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('turma', '0007_alter_diarioeletronico_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioEletronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_letivo', models.CharField(max_length=4, verbose_name='Período Letivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Diário Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.disciplina', verbose_name='Disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Diário Eletrônico',
                'verbose_name_plural': 'Diários Eletrônicos',
                'ordering': ['turma__nome', 'disciplina__nome'],
                'unique_together': {('turma', 'disciplina', 'periodo_letivo')},
            },
        ),
        migrations.CreateModel(
            name='DiarioOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data de Acesso')),
                ('ultima_atividade', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.disciplina', verbose_name='Disciplina')),
                ('divisao_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.divisaoperiodoletivo', verbose_name='Divisão do Período')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Acesso ao Diário Online',
                'verbose_name_plural': 'Acessos ao Diário Online',
                'unique_together': {('turma', 'disciplina', 'divisao_periodo', 'professor')},
            },
        ),
        migrations.CreateModel(
            name='ConteudoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(verbose_name='Data da Aula')),
                ('conteudo_lecionado', models.TextField(verbose_name='Conteúdo/Matéria Lecionada')),
                ('modulo_registrado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Módulo Registrado')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Registrou')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='diario.diarioonline', verbose_name='Diário')),
            ],
            options={
                'verbose_name': 'Conteúdo de Aula',
                'verbose_name_plural': 'Conteúdos de Aulas',
                'ordering': ['-data_aula'],
                'unique_together': {('diario', 'data_aula')},
            },
        ),
        migrations.CreateModel(
            name='RegistroChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chamada', models.DateField(verbose_name='Data da Chamada')),
                ('situacao', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Ausente Justificado')], default='PRESENTE', max_length=15, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='diario.diarioeletronico', verbose_name='Diário')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Chamada',
                'verbose_name_plural': 'Registros de Chamada',
                'ordering': ['data_chamada', 'aluno__nome'],
                'unique_together': {('diario', 'aluno', 'data_chamada')},
            },
        ),
        migrations.CreateModel(
            name='RegistroNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Lançamento')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('conceito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turma.conceito', verbose_name='Conceito')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='diario.diarioeletronico', verbose_name='Diário')),
                ('divisao_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.divisaoperiodoletivo', verbose_name='Período')),
                ('usuario_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Lançou')),
            ],
            options={
                'verbose_name': 'Registro de Nota',
                'verbose_name_plural': 'Registros de Notas',
                'ordering': ['aluno__nome'],
                'unique_together': {('diario', 'aluno', 'divisao_periodo')},
            },
        ),
    ]
