# Generated by Django 5.2.6 on 2025-09-25 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diarioeletronico',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AddField(
            model_name='diarioeletronico',
            name='data_reabertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Reabertura'),
        ),
        migrations.AddField(
            model_name='diarioeletronico',
            name='diario_fechado',
            field=models.BooleanField(default=False, verbose_name='Diário Fechado'),
        ),
        migrations.AddField(
            model_name='diarioeletronico',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável'),
        ),
        migrations.AddField(
            model_name='diarioeletronico',
            name='usuario_fechamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diarios_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Fechou'),
        ),
        migrations.AddField(
            model_name='diarioeletronico',
            name='usuario_reabertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diarios_reabertos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Reabriu'),
        ),
        migrations.AlterField(
            model_name='diarioeletronico',
            name='periodo_letivo',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Período Letivo'),
        ),
    ]
