# Generated by Django 5.2.5 on 2025-08-22 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('nome_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Pai')),
                ('mae_nao_declarada', models.BooleanField(default=False, verbose_name='Mãe não declarada')),
                ('pai_nao_declarado', models.BooleanField(default=False, verbose_name='Pai não declarado')),
                ('aluno_gemeo', models.BooleanField(default=False, verbose_name='Aluno Gêmeo')),
                ('falta_historico_escolar', models.BooleanField(default=False, verbose_name='Falta histórico escolar')),
                ('aluno_exclusivo_aee', models.BooleanField(default=False, verbose_name='Aluno exclusivo de Atividade Complementar/AEE')),
                ('tipo_arquivo', models.CharField(choices=[('CORRENTE', 'Arquivo Corrente'), ('PERMANENTE', 'Arquivo Permanente')], default='CORRENTE', max_length=20, verbose_name='Tipo de Arquivo')),
                ('lembrete', models.TextField(blank=True, null=True, verbose_name='Lembrete')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/fotos/', verbose_name='Foto')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Cadastrou')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('certidao_nascimento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Certidão de Nascimento')),
                ('titulo_eleitor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Título de Eleitor')),
                ('aluno_nao_possui_documentos', models.BooleanField(default=False, verbose_name='O(a) Aluno(a) não possui os documentos')),
                ('escola_nao_recebeu_documentos', models.BooleanField(default=False, verbose_name='A escola não dispõe ou não recebeu os documentos')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentacao', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Documentação do Aluno',
                'verbose_name_plural': 'Documentações dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Responsável')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='TransporteAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utiliza_transporte', models.BooleanField(default=False, verbose_name='Utiliza Transporte Escolar')),
                ('nome_motorista', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Motorista')),
                ('placa_veiculo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo')),
                ('rota', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rota')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Transporte do Aluno',
                'verbose_name_plural': 'Transportes dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_administrativo', models.IntegerField(verbose_name='Ano Administrativo')),
                ('tipo_ensino', models.CharField(choices=[('INFANTIL', 'Educação Infantil'), ('FUNDAMENTAL_I', 'Ensino Fundamental I'), ('FUNDAMENTAL_II', 'Ensino Fundamental II'), ('MEDIO', 'Ensino Médio'), ('EJA', 'Educação de Jovens e Adultos'), ('TECNICO', 'Ensino Técnico')], max_length=20, verbose_name='Tipo de Ensino')),
                ('serie_ano', models.CharField(max_length=50, verbose_name='Ano/Série/Módulo/Etapa')),
                ('tipo_matricula', models.CharField(choices=[('REGULAR', 'Regular'), ('DEPENDENCIA', 'Dependência'), ('SUPLENCIA', 'Suplência')], default='REGULAR', max_length=20, verbose_name='Tipo de Matrícula')),
                ('turno_preferencial', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20, verbose_name='Turno Preferencial')),
                ('data_matricula', models.DateField(verbose_name='Data da Matrícula')),
                ('possui_dependencia', models.BooleanField(default=False, verbose_name='Possui Dependência')),
                ('condicao_anterior', models.CharField(choices=[('NOVATO', 'Novato'), ('NOVATO_ESCOLA', 'Novato na Escola'), ('CONTINUIDADE', 'Continuidade'), ('RETORNANDO', 'Retornando')], max_length=20, verbose_name='Condição Anterior')),
                ('escola_origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Escola de Origem')),
                ('tipo_rede_origem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Rede')),
                ('pais_origem', models.CharField(blank=True, max_length=100, null=True, verbose_name='País de Origem')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20, verbose_name='Status')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('motivo_encerramento', models.TextField(blank=True, null=True, verbose_name='Motivo do Encerramento')),
                ('condicoes_especiais_avaliacao', models.BooleanField(default=False, verbose_name='Condições Especiais de Avaliação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='alunos.aluno')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_cadastradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-ano_administrativo', '-data_matricula'],
                'unique_together': {('aluno', 'ano_administrativo', 'tipo_matricula')},
            },
        ),
    ]
