# Generated by Django 5.2.5 on 2025-08-23 01:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioFuncionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('funcionalidade', models.CharField(choices=[('INCLUIR', 'Incluir'), ('ALTERAR', 'Alterar'), ('EXCLUIR', 'Excluir'), ('TODOS', 'Todas as Funcionalidades')], max_length=20, verbose_name='Funcionalidade')),
                ('tipo_bloqueio', models.CharField(choices=[('DIRETO', 'Bloqueio Direto'), ('POR_ANO', 'Por Ano Administrativo'), ('POR_TIPO_ENSINO', 'Por Tipo de Ensino')], max_length=20, verbose_name='Tipo de Bloqueio')),
                ('ano_administrativo', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano Administrativo')),
                ('tipo_ensino', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Ensino')),
                ('ativo', models.BooleanField(default=True, verbose_name='Bloqueio Ativo')),
                ('motivo', models.TextField(verbose_name='Motivo do Bloqueio')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início do Bloqueio')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim do Bloqueio')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Criou')),
            ],
            options={
                'verbose_name': 'Bloqueio de Funcionalidade',
                'verbose_name_plural': 'Bloqueios de Funcionalidades',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave da Configuração')),
                ('valor', models.TextField(verbose_name='Valor da Configuração')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo_valor', models.CharField(choices=[('STRING', 'Texto'), ('INTEGER', 'Número Inteiro'), ('BOOLEAN', 'Verdadeiro/Falso'), ('JSON', 'JSON')], default='STRING', max_length=20, verbose_name='Tipo do Valor')),
                ('editavel', models.BooleanField(default=True, verbose_name='Editável')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Último Usuário')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='DadoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=100, verbose_name='Rótulo')),
                ('tipo_campo', models.CharField(choices=[('TEXTO', 'Campo de Texto'), ('TEXTAREA', 'Área de Texto'), ('NUMERO', 'Número'), ('DATA', 'Data'), ('CHECKBOX', 'Checkbox'), ('SELECT', 'Lista de Seleção')], default='TEXTO', max_length=20, verbose_name='Tipo do Campo')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Campo Obrigatório')),
                ('opcoes', models.TextField(blank=True, help_text='Para campos SELECT, liste as opções separadas por vírgula', null=True, verbose_name='Opções (para SELECT)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Campo Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Dado Adicional',
                'verbose_name_plural': 'Dados Adicionais',
                'ordering': ['ordem', 'rotulo'],
            },
        ),
        migrations.CreateModel(
            name='GrupoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Grupo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Grupo Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Grupo de Acesso',
                'verbose_name_plural': 'Grupos de Acesso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Instituição')),
                ('tipo_instituicao', models.CharField(choices=[('ESCOLA', 'Escola'), ('SME', 'Secretaria Municipal de Educação'), ('SEE', 'Secretaria Estadual de Educação'), ('ORGAO_SUPERIOR', 'Órgão Superior')], max_length=20, verbose_name='Tipo')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Instituição Ativa')),
                ('instituicao_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilitarios.instituicao', verbose_name='Instituição Superior')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Configuração')),
                ('ano_administrativo', models.CharField(default='2025', max_length=4, verbose_name='Ano Administrativo')),
                ('tipo_ensino', models.CharField(max_length=50, verbose_name='Tipo de Ensino')),
                ('serie', models.CharField(max_length=50, verbose_name='Série')),
                ('turno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Turno')),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Configuração de Matrícula Rápida',
                'verbose_name_plural': 'Configurações de Matrícula Rápida',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato XXX.XXX.XXX-XX')], verbose_name='CPF (Login)')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('primeiro_acesso', models.BooleanField(default=True, verbose_name='Primeiro Acesso')),
                ('senha_temporaria', models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha Temporária')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Ação')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Alteração'), ('DELETE', 'Exclusão'), ('VIEW', 'Consulta'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PRINT', 'Impressão')], max_length=10, verbose_name='Ação')),
                ('tela', models.CharField(max_length=100, verbose_name='Tela/Módulo')),
                ('funcionalidade', models.CharField(max_length=100, verbose_name='Funcionalidade')),
                ('descricao', models.TextField(verbose_name='Descrição da Ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('dados_alterados', models.JSONField(blank=True, null=True, verbose_name='Dados Alterados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Peso')),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Valor Máximo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Tipo Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tipo de Avaliação',
                'verbose_name_plural': 'Tipos de Avaliação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CabecalhoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.IntegerField(verbose_name='Número da Linha')),
                ('tipo_conteudo', models.CharField(choices=[('BRASAO', 'Brasão'), ('TEXTO_PADRAO', 'Texto Padrão'), ('TEXTO_LIVRE', 'Texto Livre'), ('VAZIO', 'Linha Vazia')], max_length=20, verbose_name='Tipo de Conteúdo')),
                ('conteudo', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('alinhamento', models.CharField(choices=[('ESQUERDA', 'Esquerda'), ('CENTRO', 'Centro'), ('DIREITA', 'Direita')], default='CENTRO', max_length=10, verbose_name='Alinhamento')),
                ('tamanho_fonte', models.IntegerField(default=12, verbose_name='Tamanho da Fonte')),
                ('negrito', models.BooleanField(default=False, verbose_name='Negrito')),
                ('ativo', models.BooleanField(default=True, verbose_name='Linha Ativa')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Atualizou')),
            ],
            options={
                'verbose_name': 'Linha do Cabeçalho',
                'verbose_name_plural': 'Linhas do Cabeçalho',
                'ordering': ['linha'],
                'unique_together': {('linha',)},
            },
        ),
        migrations.CreateModel(
            name='AssociacaoUsuarioInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Associação Ativa')),
                ('data_associacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Associação')),
                ('data_inativacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('usuario_associacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Associou')),
                ('grupo_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilitarios.grupoacesso', verbose_name='Grupo de Acesso')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilitarios.instituicao', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Associação Usuário-Instituição',
                'verbose_name_plural': 'Associações Usuário-Instituição',
                'unique_together': {('usuario', 'instituicao', 'grupo_acesso')},
            },
        ),
        migrations.CreateModel(
            name='PermissaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('submenu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Submenu')),
                ('funcionalidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Funcionalidade')),
                ('visualizar', models.BooleanField(default=False, verbose_name='Visualizar')),
                ('incluir', models.BooleanField(default=False, verbose_name='Incluir')),
                ('alterar', models.BooleanField(default=False, verbose_name='Alterar')),
                ('excluir', models.BooleanField(default=False, verbose_name='Excluir')),
                ('imprimir', models.BooleanField(default=False, verbose_name='Imprimir')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='utilitarios.grupoacesso', verbose_name='Grupo de Acesso')),
            ],
            options={
                'verbose_name': 'Permissão de Grupo',
                'verbose_name_plural': 'Permissões de Grupos',
                'unique_together': {('grupo', 'modulo', 'submenu', 'funcionalidade')},
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('motivo', models.TextField(verbose_name='Motivo da Transferência')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('escola_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recebidas', to='utilitarios.instituicao', verbose_name='Escola de Destino')),
                ('escola_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='utilitarios.instituicao', verbose_name='Escola de Origem')),
                ('usuario_processamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Processou')),
                ('usuario_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Solicitou')),
            ],
            options={
                'verbose_name': 'Solicitação de Transferência',
                'verbose_name_plural': 'Solicitações de Transferência',
                'ordering': ['-data_solicitacao'],
                'unique_together': {('aluno', 'escola_origem', 'escola_destino', 'status')},
            },
        ),
        migrations.CreateModel(
            name='ValorDadoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_adicionais', to='alunos.aluno', verbose_name='Aluno')),
                ('dado_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilitarios.dadoadicional', verbose_name='Campo Adicional')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Atualizou')),
            ],
            options={
                'verbose_name': 'Valor de Dado Adicional',
                'verbose_name_plural': 'Valores de Dados Adicionais',
                'unique_together': {('aluno', 'dado_adicional')},
            },
        ),
    ]
