# Generated by Django 5.2.5 on 2025-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_documentacaofuncionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacaofuncionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
