# Generated by Django 5.2.5 on 2025-08-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_funcionario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosfuncionais',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
    ]
