# Generated by Django 5.2.5 on 2025-08-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_dadosfuncionais_data_admissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ativo',
        ),
    ]
