# Generated by Django 5.2.5 on 2025-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_remove_funcionario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, verbose_name='Sexo'),
        ),
    ]
