# Generated by Django 5.2.5 on 2025-08-23 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItinerarioFormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Itinerário')),
                ('carga_horaria_total', models.IntegerField(verbose_name='Carga Horária Total')),
                ('areas_conhecimento', models.CharField(choices=[('LINGUAGENS', 'Linguagens e suas Tecnologias'), ('MATEMATICA', 'Matemática e suas Tecnologias'), ('NATUREZA', 'Ciências da Natureza e suas Tecnologias'), ('HUMANAS', 'Ciências Humanas e Sociais Aplicadas'), ('TECNICA', 'Formação Técnica e Profissional')], max_length=50, verbose_name='Área de Conhecimento')),
                ('habilidades', models.TextField(verbose_name='Habilidades')),
                ('vagas_disponiveis', models.IntegerField(default=30, verbose_name='Vagas Disponíveis')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Itinerário Formativo',
                'verbose_name_plural': 'Itinerários Formativos',
            },
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Unidade')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('habilidades_especificas', models.TextField(verbose_name='Habilidades Específicas')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidade Curricular',
                'verbose_name_plural': 'Unidades Curriculares',
            },
        ),
        migrations.CreateModel(
            name='EnturmacaoItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_enturmacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='alunos.aluno')),
                ('usuario_enturmacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='escola.itinerarioformativo')),
            ],
            options={
                'verbose_name': 'Enturmação em Itinerário',
                'verbose_name_plural': 'Enturmações em Itinerários',
                'unique_together': {('aluno', 'itinerario')},
            },
        ),
        migrations.CreateModel(
            name='AssociacaoItinerarioUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem na Grade')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='escola.itinerarioformativo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.unidadecurricular')),
            ],
            options={
                'verbose_name': 'Associação Itinerário-Unidade',
                'verbose_name_plural': 'Associações Itinerário-Unidade',
                'unique_together': {('itinerario', 'unidade')},
            },
        ),
    ]
