# Generated by Django 5.2.5 on 2025-08-23 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criou'), ('EDITAR', 'Editou'), ('DELETAR', 'Deletou'), ('VISUALIZAR', 'Visualizou')], max_length=20, verbose_name='Ação')),
                ('modulo', models.CharField(choices=[('ALUNOS', 'Alunos'), ('FUNCIONARIOS', 'Funcionários'), ('OPCOES', 'Opções'), ('AEE', 'AEE/AC'), ('AVALIACAO', 'Avaliação'), ('UTILITARIOS', 'Utilitários'), ('DASHBOARD', 'Dashboard')], max_length=20, verbose_name='Módulo')),
                ('objeto_nome', models.CharField(max_length=255, verbose_name='Nome do Objeto')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_atividade', models.DateTimeField(auto_now_add=True, verbose_name='Data da Atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atividade Recente',
                'verbose_name_plural': 'Atividades Recentes',
                'ordering': ['-data_atividade'],
            },
        ),
    ]
