# Generated by Django 5.2.5 on 2025-08-23 01:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('tipo_projeto', models.CharField(choices=[('AEE', 'Atendimento Educacional Especializado'), ('AC', 'Atividade Complementar')], max_length=10, verbose_name='Tipo de Projeto')),
                ('periodo_letivo', models.CharField(default='2025', max_length=4, verbose_name='Período Letivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('carga_horaria', models.IntegerField(default=20, verbose_name='Carga Horária Semanal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Projeto Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Projeto Pedagógico',
                'verbose_name_plural': 'Projetos Pedagógicos',
                'ordering': ['-periodo_letivo', 'tipo_projeto', 'nome'],
                'unique_together': {('nome', 'periodo_letivo')},
            },
        ),
        migrations.CreateModel(
            name='TurmaAEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Turma')),
                ('periodo_letivo', models.CharField(default='2025', max_length=4, verbose_name='Período Letivo')),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=15, verbose_name='Turno')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Término')),
                ('maximo_alunos', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Número Máximo de Alunos')),
                ('ordenacao', models.CharField(choices=[('ALFABETICA', 'Alfabética'), ('DATA_NASCIMENTO', 'Data de Nascimento'), ('CODIGO', 'Código do Aluno'), ('PERSONALIZADA', 'Personalizada')], default='ALFABETICA', max_length=20, verbose_name='Ordenação')),
                ('segunda', models.BooleanField(default=False, verbose_name='Segunda-feira')),
                ('terca', models.BooleanField(default=False, verbose_name='Terça-feira')),
                ('quarta', models.BooleanField(default=False, verbose_name='Quarta-feira')),
                ('quinta', models.BooleanField(default=False, verbose_name='Quinta-feira')),
                ('sexta', models.BooleanField(default=False, verbose_name='Sexta-feira')),
                ('sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('atividade_especifica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Atividade Específica')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local/Sala')),
                ('material_necessario', models.TextField(blank=True, null=True, verbose_name='Material Necessário')),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=15, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('projeto_pedagogico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aee.projetopedagogico', verbose_name='Projeto Pedagógico')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas_aee_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Turma AEE/AC',
                'verbose_name_plural': 'Turmas AEE/AC',
                'ordering': ['-periodo_letivo', 'turno', 'nome'],
                'unique_together': {('nome', 'periodo_letivo')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoEnturmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('ADICIONAR', 'Aluno Adicionado'), ('REMOVER', 'Aluno Removido'), ('REORDENAR', 'Lista Reordenada')], max_length=15, verbose_name='Ação Realizada')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='aee.turmaaee', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Histórico de Enturmação',
                'verbose_name_plural': 'Histórico de Enturmações',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='AssociacaoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola_atual', models.CharField(max_length=255, verbose_name='Escola Atual')),
                ('escola_origem', models.CharField(max_length=255, verbose_name='Escola de Origem')),
                ('data_associacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Associação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Associação Ativa')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('usuario_associacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Associou')),
            ],
            options={
                'verbose_name': 'Associação de Escola',
                'verbose_name_plural': 'Associações de Escolas',
                'unique_together': {('aluno', 'escola_atual')},
            },
        ),
        migrations.CreateModel(
            name='EnturmacaoAEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('PROPRIA_ESCOLA', 'Alunos da própria escola'), ('OUTRA_ESCOLA_REDE', 'Alunos de outra escola da rede municipal'), ('EXCLUSIVO_AEE', 'Alunos exclusivos de AEE/AC')], max_length=20, verbose_name='Origem do Aluno')),
                ('escola_origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Escola de Origem')),
                ('codigo_escola_origem', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Escola')),
                ('ano_administrativo', models.CharField(max_length=4, verbose_name='Ano Administrativo')),
                ('tipo_ensino', models.CharField(max_length=50, verbose_name='Tipo de Ensino')),
                ('ano_serie', models.CharField(max_length=50, verbose_name='Ano/Série/Módulo/Etapa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Enturmação Ativa')),
                ('data_enturmacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Enturmação')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enturmacoes_aee', to='alunos.aluno', verbose_name='Aluno')),
                ('usuario_enturmacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Enturmou')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enturmacoes', to='aee.turmaaee', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Enturmação AEE/AC',
                'verbose_name_plural': 'Enturmações AEE/AC',
                'ordering': ['turma', 'aluno__nome'],
                'unique_together': {('turma', 'aluno', 'ativo')},
            },
        ),
    ]
