# Generated by Django 5.2.5 on 2025-09-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_diarioeletronico_registrochamada_registronota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano_serie',
            field=models.CharField(choices=[('BERÇARIO', 'Berçário'), ('MATERNAL_I', 'Maternal I'), ('MATERNAL_II', 'Maternal II'), ('PRE_I', 'Pré I'), ('PRE_II', 'Pré II'), ('1_ANO', '1º Ano'), ('2_ANO', '2º Ano'), ('3_ANO', '3º Ano'), ('4_ANO', '4º Ano'), ('5_ANO', '5º Ano'), ('6_ANO', '6º Ano'), ('7_ANO', '7º Ano'), ('8_ANO', '8º Ano'), ('9_ANO', '9º Ano'), ('1_ANO_EM', '1º Ano'), ('2_ANO_EM', '2º Ano'), ('3_ANO_EM', '3º Ano')], max_length=50, verbose_name='Ano/Série'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tipo_ensino',
            field=models.CharField(choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('ENSINO_FUNDAMENTAL_I', 'Ensino Fundamental I'), ('ENSINO_FUNDAMENTAL_II', 'Ensino Fundamental II'), ('ENSINO_MEDIO', 'Ensino Médio')], max_length=50, verbose_name='Tipo de Ensino'),
        ),
    ]
