# Generated by Django 5.2.6 on 2025-09-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('avaliacao', '0005_alter_turma_ano_serie_alter_turma_tipo_ensino'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enturmacao',
            unique_together={('aluno', 'ativo')},
        ),
    ]
