# Generated by Django 5.2.5 on 2025-08-23 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('FICHA_MATRICULA', 'Ficha de Matrícula'), ('BOLETIM', 'Boletim'), ('FICHA_INDIVIDUAL', 'Ficha Individual'), ('DIAGNOSTICO_HABILIDADES', 'Diagnóstico de Habilidades')], max_length=100, unique=True, verbose_name='Nome do Relatório')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Relatório Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Relatório',
                'verbose_name_plural': 'Tipos de Relatórios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_letivo', models.CharField(default='2025', max_length=4, verbose_name='Período Letivo')),
                ('tipo_ensino', models.CharField(choices=[('INFANTIL', 'Educação Infantil'), ('FUNDAMENTAL_I', 'Ensino Fundamental I'), ('FUNDAMENTAL_II', 'Ensino Fundamental II'), ('MEDIO', 'Ensino Médio'), ('EJA', 'Educação de Jovens e Adultos'), ('ESPECIAL', 'Educação Especial')], max_length=20, verbose_name='Tipo de Ensino')),
                ('serie', models.CharField(choices=[('1_ANO', '1º Ano'), ('2_ANO', '2º Ano'), ('3_ANO', '3º Ano'), ('4_ANO', '4º Ano'), ('5_ANO', '5º Ano'), ('6_ANO', '6º Ano'), ('7_ANO', '7º Ano'), ('8_ANO', '8º Ano'), ('9_ANO', '9º Ano'), ('1_MEDIO', '1º Ano - Ensino Médio'), ('2_MEDIO', '2º Ano - Ensino Médio'), ('3_MEDIO', '3º Ano - Ensino Médio'), ('MULTI', 'Multisseriada')], max_length=15, verbose_name='Série')),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=15, verbose_name='Turno')),
                ('data_inicio_letivo', models.DateField(verbose_name='Início do Ano Letivo')),
                ('data_fim_letivo', models.DateField(verbose_name='Fim do Ano Letivo')),
                ('dias_letivos', models.IntegerField(default=200, verbose_name='Dias Letivos')),
                ('dias_escolares', models.IntegerField(default=200, verbose_name='Dias Escolares')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Calendário Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Calendário Escolar',
                'verbose_name_plural': 'Calendários Escolares',
                'ordering': ['-periodo_letivo', 'tipo_ensino', 'serie', 'turno'],
                'unique_together': {('periodo_letivo', 'tipo_ensino', 'serie', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='FiltroRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_letivo', models.CharField(default='2025', max_length=4, verbose_name='Período Letivo')),
                ('tipo_ensino', models.CharField(choices=[('INFANTIL', 'Educação Infantil'), ('FUNDAMENTAL_I', 'Ensino Fundamental I'), ('FUNDAMENTAL_II', 'Ensino Fundamental II'), ('MEDIO', 'Ensino Médio'), ('EJA', 'Educação de Jovens e Adultos'), ('ESPECIAL', 'Educação Especial'), ('TODOS', 'Todos')], default='TODOS', max_length=20, verbose_name='Tipo de Ensino')),
                ('ano_serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ano/Série/Módulo/Etapa')),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral'), ('TODOS', 'Todos')], default='TODOS', max_length=15, verbose_name='Turno')),
                ('status_diario', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('TODOS', 'Todos')], default='TODOS', max_length=10, verbose_name='Status do Diário')),
                ('situacao_turma', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('TODOS', 'Todos')], default='TODOS', max_length=15, verbose_name='Situação da Turma')),
                ('data_filtro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Filtro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tipo_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcoes.tiporelatorio', verbose_name='Tipo de Relatório')),
            ],
            options={
                'verbose_name': 'Filtro de Relatório',
                'verbose_name_plural': 'Filtros de Relatórios',
                'ordering': ['-data_filtro'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('tipo_evento', models.CharField(choices=[('AULA', 'Dia de Aula'), ('FERIADO', 'Feriado'), ('RECESSO', 'Recesso'), ('EVENTO_ESPECIAL', 'Evento Especial'), ('REUNIAO_PEDAGOGICA', 'Reunião Pedagógica'), ('FORMACAO', 'Formação/Capacitação')], max_length=20, verbose_name='Tipo de Evento')),
                ('nome_evento', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dia_letivo', models.BooleanField(default=True, verbose_name='Conta como Dia Letivo')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='opcoes.calendarioescolar', verbose_name='Calendário')),
            ],
            options={
                'verbose_name': 'Evento do Calendário',
                'verbose_name_plural': 'Eventos do Calendário',
                'ordering': ['data_evento'],
                'unique_together': {('calendario', 'data_evento', 'nome_evento')},
            },
        ),
    ]
