# Generated by Django 5.2.5 on 2025-08-23 01:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Disciplina')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Disciplina')),
                ('avalia_por_conceito', models.BooleanField(default=False, verbose_name='Avalia por Conceito')),
                ('carga_horaria', models.IntegerField(default=40, verbose_name='Carga Horária')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disciplina Ativa')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conceito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, unique=True, verbose_name='Nome do Conceito')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor_numerico', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Valor Numérico Equivalente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Conceito Ativo')),
                ('cor_display', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor para Exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Conceito',
                'verbose_name_plural': 'Conceitos',
                'ordering': ['valor_numerico'],
            },
        ),
        migrations.CreateModel(
            name='DivisaoPeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Divisão')),
                ('tipo_divisao', models.CharField(choices=[('BIMESTRE', 'Bimestre'), ('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('ANUAL', 'Anual')], max_length=15, verbose_name='Tipo de Divisão')),
                ('periodo_letivo', models.CharField(max_length=4, verbose_name='Período Letivo')),
                ('ordem', models.IntegerField(verbose_name='Ordem')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Divisão Ativa')),
            ],
            options={
                'verbose_name': 'Divisão do Período Letivo',
                'verbose_name_plural': 'Divisões do Período Letivo',
                'ordering': ['periodo_letivo', 'ordem'],
                'unique_together': {('periodo_letivo', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='GrupoConceito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Grupo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Grupo Ativo')),
                ('conceitos', models.ManyToManyField(to='turma.conceito', verbose_name='Conceitos do Grupo')),
            ],
            options={
                'verbose_name': 'Grupo de Conceito',
                'verbose_name_plural': 'Grupos de Conceitos',
            },
        ),
        migrations.CreateModel(
            name='HabilidadeCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Habilidade/Competência')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Habilidade/Competência',
                'verbose_name_plural': 'Habilidades/Competências',
                'ordering': ['disciplina', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Turma')),
                ('periodo_letivo', models.CharField(default='2025', max_length=4, verbose_name='Período Letivo')),
                ('tipo_ensino', models.CharField(max_length=50, verbose_name='Tipo de Ensino')),
                ('ano_serie', models.CharField(max_length=50, verbose_name='Ano/Série')),
                ('turno', models.CharField(max_length=20, verbose_name='Turno')),
                ('diario_fechado', models.BooleanField(default=False, verbose_name='Diário Fechado')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'unique_together': {('nome', 'periodo_letivo')},
            },
        ),
        migrations.CreateModel(
            name='DiarioOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data de Acesso')),
                ('ultima_atividade', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.disciplina', verbose_name='Disciplina')),
                ('divisao_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.divisaoperiodoletivo', verbose_name='Divisão do Período')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Acesso ao Diário Online',
                'verbose_name_plural': 'Acessos ao Diário Online',
                'unique_together': {('turma', 'disciplina', 'divisao_periodo', 'professor')},
            },
        ),
        migrations.CreateModel(
            name='AtestadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atestado', models.DateField(verbose_name='Data do Atestado')),
                ('numero_dias', models.IntegerField(verbose_name='Número de Dias')),
                ('faltas_justificadas', models.IntegerField(verbose_name='Número de Faltas Justificadas')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Cadastrou')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Atestado Médico',
                'verbose_name_plural': 'Atestados Médicos',
                'ordering': ['-data_atestado'],
            },
        ),
        migrations.CreateModel(
            name='ConteudoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(verbose_name='Data da Aula')),
                ('conteudo_lecionado', models.TextField(verbose_name='Conteúdo/Matéria Lecionada')),
                ('modulo_registrado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Módulo Registrado')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Registrou')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='turma.diarioonline', verbose_name='Diário')),
            ],
            options={
                'verbose_name': 'Conteúdo de Aula',
                'verbose_name_plural': 'Conteúdos de Aulas',
                'ordering': ['-data_aula'],
                'unique_together': {('diario', 'data_aula')},
            },
        ),
        migrations.CreateModel(
            name='RecuperacaoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_atual', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota Atual')),
                ('nota_recuperacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota da Recuperação')),
                ('nao_optou', models.BooleanField(default=False, verbose_name='Não Optou pela Recuperação')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Lançamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.disciplina', verbose_name='Disciplina')),
                ('usuario_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Lançou')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Recuperação Especial',
                'verbose_name_plural': 'Recuperações Especiais',
                'unique_together': {('turma', 'disciplina', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='PendenciaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pendencia', models.CharField(choices=[('NOTA_NAO_INFORMADA', 'Nota não informada'), ('FREQUENCIA_NAO_INFORMADA', 'Frequência não informada'), ('CONCEITO_NAO_INFORMADO', 'Conceito não informado'), ('PARECER_NAO_INFORMADO', 'Parecer não informado')], max_length=30, verbose_name='Tipo de Pendência')),
                ('resolvida', models.BooleanField(default=False, verbose_name='Pendência Resolvida')),
                ('data_identificacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Identificação')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.disciplina', verbose_name='Disciplina')),
                ('divisao_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.divisaoperiodoletivo', verbose_name='Divisão do Período')),
                ('usuario_resolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Resolveu')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Pendência de Avaliação',
                'verbose_name_plural': 'Pendências de Avaliação',
                'unique_together': {('turma', 'disciplina', 'divisao_periodo', 'aluno', 'tipo_pendencia')},
            },
        ),
        migrations.CreateModel(
            name='ParecerDescritivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Lançamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('conceito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turma.conceito', verbose_name='Conceito')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.disciplina', verbose_name='Disciplina')),
                ('divisao_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.divisaoperiodoletivo', verbose_name='Divisão do Período')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.habilidadecompetencia', verbose_name='Habilidade/Competência')),
                ('usuario_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Lançou')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Parecer Descritivo',
                'verbose_name_plural': 'Pareceres Descritivos',
                'unique_together': {('turma', 'disciplina', 'divisao_periodo', 'aluno', 'habilidade')},
            },
        ),
        migrations.CreateModel(
            name='MediaGlobalConceito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia_percentual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Frequência %')),
                ('total_faltas', models.IntegerField(default=0, verbose_name='Total de Faltas')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Lançamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('conceito_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turma.conceito', verbose_name='Conceito Global')),
                ('usuario_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Lançou')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Média Global por Conceito',
                'verbose_name_plural': 'Médias Globais por Conceito',
                'unique_together': {('turma', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='LancamentoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota')),
                ('aulas_previstas', models.IntegerField(default=0, verbose_name='Quantidade de Aulas Previstas')),
                ('aulas_lecionadas', models.IntegerField(default=0, verbose_name='Quantidade de Aulas Lecionadas')),
                ('faltas', models.IntegerField(default=0, verbose_name='Número de Faltas')),
                ('faltas_justificadas', models.IntegerField(default=0, verbose_name='Faltas Justificadas')),
                ('tipo_lancamento', models.CharField(choices=[('AVALIACAO_FREQUENCIA', 'Avaliação/Frequência'), ('AVALIACAO', 'Avaliação'), ('FREQUENCIA', 'Frequência')], max_length=25, verbose_name='Tipo de Lançamento')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Lançamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('conceito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turma.conceito', verbose_name='Conceito')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.disciplina', verbose_name='Disciplina')),
                ('divisao_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.divisaoperiodoletivo', verbose_name='Divisão do Período')),
                ('usuario_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Lançou')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Lançamento de Nota/Frequência',
                'verbose_name_plural': 'Lançamentos de Notas/Frequência',
                'unique_together': {('turma', 'disciplina', 'divisao_periodo', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDescritiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes_descricao_global', models.TextField(verbose_name='Observações / Descrição Global')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Lançamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('usuario_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Lançou')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turma.disciplina', verbose_name='Disciplina')),
                ('divisao_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.divisaoperiodoletivo', verbose_name='Divisão do Período')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Avaliação Descritiva',
                'verbose_name_plural': 'Avaliações Descritivas',
                'unique_together': {('turma', 'aluno', 'divisao_periodo', 'disciplina')},
            },
        ),
    ]
