# Generated by Django 5.2.5 on 2025-08-24 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('turma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['periodo_letivo', 'ano_serie', 'nome'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AddField(
            model_name='turma',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='turma',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='turma',
            name='vagas_total',
            field=models.IntegerField(default=30, verbose_name='Total de Vagas'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano_serie',
            field=models.CharField(choices=[('BERÇARIO', 'Berçário'), ('MATERNAL_I', 'Maternal I'), ('MATERNAL_II', 'Maternal II'), ('PRE_I', 'Pré I'), ('PRE_II', 'Pré II'), ('1_ANO', '1º Ano'), ('2_ANO', '2º Ano'), ('3_ANO', '3º Ano'), ('4_ANO', '4º Ano'), ('5_ANO', '5º Ano'), ('6_ANO', '6º Ano'), ('7_ANO', '7º Ano'), ('8_ANO', '8º Ano'), ('9_ANO', '9º Ano'), ('1_SERIE', '1ª Série'), ('2_SERIE', '2ª Série'), ('3_SERIE', '3ª Série')], max_length=50, verbose_name='Ano/Série'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tipo_ensino',
            field=models.CharField(choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('ENSINO_FUNDAMENTAL_I', 'Ensino Fundamental I'), ('ENSINO_FUNDAMENTAL_II', 'Ensino Fundamental II'), ('ENSINO_MEDIO', 'Ensino Médio'), ('EJA', 'Educação de Jovens e Adultos'), ('TECNICO', 'Técnico')], max_length=50, verbose_name='Tipo de Ensino'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20, verbose_name='Turno'),
        ),
        migrations.CreateModel(
            name='Enturmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_enturmacao', models.DateField(auto_now_add=True, verbose_name='Data de Enturmação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Enturmação Ativa')),
                ('data_desenturmacao', models.DateField(blank=True, null=True, verbose_name='Data de Desenturmação')),
                ('motivo_desenturmacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo da Desenturmação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enturmacoes', to='alunos.aluno', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enturmacoes', to='turma.turma', verbose_name='Turma')),
                ('usuario_desenturmacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='desenturmacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Desenturmou')),
                ('usuario_enturmacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Enturmou')),
            ],
            options={
                'verbose_name': 'Enturmação',
                'verbose_name_plural': 'Enturmações',
                'ordering': ['turma', 'aluno__nome'],
                'unique_together': {('turma', 'aluno', 'ativo')},
            },
        ),
    ]
