# Generated by Django 5.2.6 on 2025-09-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0007_alter_diarioeletronico_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código da Disciplina'),
        ),
    ]
